title: "Jakub Matuszko"
email: jakub@jmat.pl
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Jakub
paginate: 30
disqus: "jmat"
locale: pl_pl
lang: pl_pl
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  sal:
    name: Jakub Matuszko
    display_name: Jakub
    avatar: 'assets/images/sal.png'
    email: jakub@jmat.pl
    web: https://www.jmat.pl
    twitter: https://twitter.com/thjacb
    description: "Student - Analityk - Programista."
# Social
social:
  instagram: https://www.instagram.com/matuszkojakub/
  facebook: https://www.facebook.com/matuszkojakub
  twitter: https://twitter.com/thjacb

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives